### ISSUE TITLE
timeout handler

### ISSUE THREAD

**Issue by f5cs** [ujjwalguptaofficial/JsStore#103]
in the jsstore,
there many promise call,in some case of exception,these promise's resolve or reject has not exe to call back.and hole jsstore  framework was hang up(promise are pending status at all time),and can't do anything more.
Do you consider it add promise timeout handler to trigger promise resolve/reject like database's timeout?

var timeout = 10000;
var timeoutHandler = {};

var interruptFn = function(uuid){
timeoutHandler[uuid].reject('timeout');
delete timeoutHandler[uuid];
}

function query(){
return new Promise(resolve,reject){
var uuid = ...;
timeoutId = setTimeout('interruptFn("'+uuid+'")',timeout);
timeoutHandler[uuid] = {rl:resolve,rj:reject,timeoutId:timeoutId};
......
await somelogic...
clearTimeout(timeoutId);
delete timeoutHandler[uuid];
}
}

**Comment by ujjwalguptaofficial** [comment]
First i need to know when its happening. You said - promises are never resolved or rejected, this is a very critical issue, i need to know any situation when its happening.

**Comment by ujjwalguptaofficial** [comment]
Timeout is not a good option in client side, because of -

* A web app can have any user & can be used at any device - from a high spec device to a low spec device like mobile with 1 gb ram. The timeout may not happen at high spec device but timeout with same time can occur on low end device.

* Sometimes a device might have a high usage means its working at its highest potential then timeout might occurs even if itimeout was handled for low spec device.

Hope this one makes sense.

**Comment by f5cs** [comment]
**The jsstore framework crash when the following error appear:**

jsstore.worker.js:234 DOMException: Failed to execute 'only' on 'IDBKeyRange': The parameter is not a valid key.
    at Instance.JsStoreWorker../src/worker/business/base_helper.ts.BaseHelper.getKeyRange (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:490:40)
    at Instance.JsStoreWorker../src/worker/business/select/where.ts.Where.executeWhereLogic (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:4553:81)
    at Instance.Base._this.goToWhereLogic (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:191:26)
    at Instance.JsStoreWorker../src/worker/business/select/instance.ts.Instance.processWhere_ (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:3644:14)
    at Instance.JsStoreWorker../src/worker/business/select/instance.ts.Instance.execute (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:3539:26)
    at executeLogic (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:3948:36)
    at Instance.onSuccess (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:3946:25)
    at Instance._this.onTransactionCompleted_ (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:3513:27)
    at IDBTransaction.onComplete (file:///G:/RD/5csApp/xledger/resources/scripts/db/jsstore.worker.js:1439:17)
JsStoreWorker../src/worker/business/base.ts.Base.onExceptionOccured @ jsstore.worker.js:234
JsStoreWorker../src/worker/business/select/instance.ts.Instance.execute @ jsstore.worker.js:3549
executeLogic @ jsstore.worker.js:3948
(anonymous) @ jsstore.worker.js:3946
Instance._this.onTransactionCompleted_ @ jsstore.worker.js:3513
onComplete @ jsstore.worker.js:1439

**Comment by f5cs** [comment]
this error is occus by join query where join column's value is null:
table1's cloumn return null vlaue, use the null vlaue as a index to query table2, And then there's the mistake.
