### ISSUE TITLE
Join Clause is not working in v3.4.2

### ISSUE THREAD

**Issue by LeeRob97** [ujjwalguptaofficial/JsStore#134]
Error:

jsstore.min.js:6 Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': HTMLTableElement object could not be cloned.
    at t.e.sendRequestToWorker_ (<mylocaldomain>/js/JSSTORE/jsstore.min.js:6:5321)
    at t.e.executeQry_ (<mylocaldomain>/js/JSSTORE/jsstore.min.js:6:4715)
    at t.e.processFinishedQuery_ (<mylocaldomain>/js/JSSTORE/jsstore.min.js:6:3844)
    at t.e.onMessageFromWorker_ (<mylocaldomain>/js/JSSTORE/jsstore.min.js:6:3304)

Use Case:
`results = await connection.select({
                from: table,
                join: {
                    with: "Address",
                    on: "People.id=Address.pid"
                }
            });`

I am trying to join to tables that share on table 1 ID number which is of type number and everytime I try I get the error shown above

**Comment by LeeRob97** [comment]
Nevermind I was using the wrong variable it works just fine, sorry.
